/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ProtectedRouteImport } from './routes/_protected/route'
import { Route as ProtectedIndexImport } from './routes/_protected/index'
import { Route as ProtectedWorkspaceImport } from './routes/_protected/workspace'
import { Route as ProtectedBImport } from './routes/_protected/b'
import { Route as authLoginImport } from './routes/(auth)/login'

// Create/Update Routes

const ProtectedRouteRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRoute,
} as any)

const ProtectedIndexRoute = ProtectedIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)

const ProtectedWorkspaceRoute = ProtectedWorkspaceImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => ProtectedRouteRoute,
} as any)

const ProtectedBRoute = ProtectedBImport.update({
  id: '/b',
  path: '/b',
  getParentRoute: () => ProtectedRouteRoute,
} as any)

const authLoginRoute = authLoginImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginImport
      parentRoute: typeof rootRoute
    }
    '/_protected/b': {
      id: '/_protected/b'
      path: '/b'
      fullPath: '/b'
      preLoaderRoute: typeof ProtectedBImport
      parentRoute: typeof ProtectedRouteImport
    }
    '/_protected/workspace': {
      id: '/_protected/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof ProtectedWorkspaceImport
      parentRoute: typeof ProtectedRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexImport
      parentRoute: typeof ProtectedRouteImport
    }
  }
}

// Create and export the route tree

interface ProtectedRouteRouteChildren {
  ProtectedBRoute: typeof ProtectedBRoute
  ProtectedWorkspaceRoute: typeof ProtectedWorkspaceRoute
  ProtectedIndexRoute: typeof ProtectedIndexRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedBRoute: ProtectedBRoute,
  ProtectedWorkspaceRoute: ProtectedWorkspaceRoute,
  ProtectedIndexRoute: ProtectedIndexRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof ProtectedRouteRouteWithChildren
  '/login': typeof authLoginRoute
  '/b': typeof ProtectedBRoute
  '/workspace': typeof ProtectedWorkspaceRoute
  '/': typeof ProtectedIndexRoute
}

export interface FileRoutesByTo {
  '/login': typeof authLoginRoute
  '/b': typeof ProtectedBRoute
  '/workspace': typeof ProtectedWorkspaceRoute
  '/': typeof ProtectedIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/_protected/b': typeof ProtectedBRoute
  '/_protected/workspace': typeof ProtectedWorkspaceRoute
  '/_protected/': typeof ProtectedIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '' | '/login' | '/b' | '/workspace' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/b' | '/workspace' | '/'
  id:
    | '__root__'
    | '/_protected'
    | '/(auth)/login'
    | '/_protected/b'
    | '/_protected/workspace'
    | '/_protected/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  authLoginRoute: typeof authLoginRoute
}

const rootRouteChildren: RootRouteChildren = {
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  authLoginRoute: authLoginRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_protected",
        "/(auth)/login"
      ]
    },
    "/_protected": {
      "filePath": "_protected/route.tsx",
      "children": [
        "/_protected/b",
        "/_protected/workspace",
        "/_protected/"
      ]
    },
    "/(auth)/login": {
      "filePath": "(auth)/login.tsx"
    },
    "/_protected/b": {
      "filePath": "_protected/b.tsx",
      "parent": "/_protected"
    },
    "/_protected/workspace": {
      "filePath": "_protected/workspace.tsx",
      "parent": "/_protected"
    },
    "/_protected/": {
      "filePath": "_protected/index.tsx",
      "parent": "/_protected"
    }
  }
}
ROUTE_MANIFEST_END */
